### ISSUE TITLE
[Crash] Conflict w/ combining Better Chesting Chest & a minecart

### ISSUE THREAD

**Issue by WenXin20** [T145/metaltransport#7]
## Problem Details
Minecraft v1.12.2
Forge v14.23.5.2838
[Better Chesting](https://www.curseforge.com/minecraft/mc-mods/betterchesting) v1.1.1
Metal Transport v2.1.1

I got this crash after trying to combine a chest with items in it (made possible with Better Chesting) with a minecart in the crafting screen of my player. I'm not sure if the it's because of this mod or if it's related to Better Chesting though.

[Crash Report](https://paste.dimdev.org/obezosirap.mccrash)

**Comment by T145** [comment]
Presently, I see no information that the problem is w/ MetalTransport. If, when you tried to crafting the resulting minecart w/ chest, got a valid output, that means my recipe was registered properly. That's only crafting interaction I have. Based on the log it seems the problem is w/ the Placebo library. If you go into Placebo's config file there should be an option to disable "fast recipes." Set that to false and see if things work out.

**Comment by WenXin20** [comment]
I reported it to Placebo first at Shadows-of-Fire/Placebo#4, but the mod author said it wasn't related to his mod. The output also didn't appear before crashing.

**Comment by WenXin20** [comment]
I can try disabling the "fast recipes" option later though.

**Comment by WenXin20** [comment]
I'm not able to reproduce this crash anymore, so hopefully it's fixed. 
Although if I right-click a Minecart with a chest with items in it, the items are lost.
It might be something that needs compatibility added for.

**Comment by T145** [comment]
It will need to be yes. The dev of better chesting can add compat through my robust api, which will have more docs after some more profiles are added in.
